### ISSUE TITLE
Create a beautifull README.md

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/galactic-space-combat#1]
Because we have to start somewhere :sweat_smile:!

**Comment by bu7ch** [comment]
**Done ! :smile:** => 66e32052bdd7a69ded85f4c790673f3dc28677fa

**Comment by yvan-sraka** [comment]
@bu7ch => http://www.francaisfacile.com/exercices/exercice-francais-2/exercice-francais-57403.php :wink:
