### ISSUE TITLE
Use PHP include keyword to don't duplicate code

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/galactic-space-combat#19]

**Comment by amare16** [comment]
I created `include.php` file and i added the **DATABASE SETTINGS** code in it, i.e.

``` php
<?php 
$HOST = 'localhost';
$DBNAME = 'test';
$LOGIN = 'root';
$PASSWORD = 'simplonco';
?>
```

And I added this file(`include.php`) in two (`api` and `includes`) directories because it is not working for me when i added it in the root, i.e. `html`.
If someone has a solution, you welcome. :wink:
