### ISSUE TITLE
Add a .htaccess to disable apache HTTP access inside includes folder

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/galactic-space-combat#3]
Disable apache HTTP access inside `includes` folder with a `.htacess`!

**Comment by sakhradam** [comment]
Added :smile: !!

**Comment by yvan-sraka** [comment]
When I do `firefox http://localhost/includes/welcome.php`, it still work on my computer..
I hope to get a **400** HTTP error :wink: !
