### ISSUE TITLE
Don't forget htmlspecialchars()

### ISSUE THREAD

**Issue by yvan-sraka** [simplonco/galactic-space-combat#8]
For example, inside `includes/control_center.php`:

``` html
<!-- TODO: Don't forget htmlspecialchars() -->
<form class="form" action="/api/create_task.php?key=<?php echo $_GET['key']; ?>" method="POST">
```

**Comment by ELmardi2** [comment]
little add but.............................;;

**Comment by yvan-sraka** [comment]
Are you sure there is no `htmlspecialchars` left to add?

**Comment by yvan-sraka** [comment]
(cf. last commit https://github.com/simplonco/big-project/commit/1ec781c1f77cd6a624704249a8510bb7c1377506)
